export default {
  noe: [
    "Titan's Revenge",
    "Thunderstroke",
    "Wizardspike",
    "Naj's Puzzler",
    "Stormshield",
    "Moser's Blessed Circle",
    "Lidless Wall",
    "Griffon's Eye",
    "Harlequin Crest",
    "Valkyrie Wing",
    "Kira's Guardian",
    "Rockstopper",
    "Tarnhelm",
    "Peasant Crown",
    "Skullder's Ire",
    "Duriel's Shell",
    "Death's Hand",
    "Sander's Taboo",
    "Laying of Hands",
    "Razortail",
    "Arachnid Mesh",
    "Thundergod's Vigor",
    "Verdungo's Hearty Cord",
    "Nosferatu's Coil",
    "Credendum",
    "War Traveler",
    "Aldur's Advance",
    "Silkweave",
    "Natalya's Soul",
    "Highlord's Wrath",
    "The Cat's Eye",
    "Mara's Kaleidoscope",
    "Raven Frost",
    "The Stone of Jordan",
    "Bul-Kathos' Wedding Band",
    "Nature's Peace",
    "Dwarf Star",
    "Manald Heal",
    "Nagelring",
    "Crack of the Heavens",
    "Suicide Branch",
    "Nightwing's Veil",
    "Crown of Ages",
    "Skin of the Vipermagi",
    "Magefist",
    "Chance Guards",
    "Bloodfist",
    "Waterwalk",
    "Sandstorm Trek",
    "Wisp Projector",
    "Bone Break",
    "Cold Rupture",
    "Wormskull",
    "Flame Rift",
    "Astreon's Iron Ward",
    "Spectral Shard",
    "Gull",
    "Trang-Oul's Claws",
    "Goldwrap",
    "Nightsmoke",
    "Immortal King's Detail",
    "Seraph's Hymn",
    "Telling of Beads",
    "Death's Guard",
    "Fleshripper",
    "The Gnasher",
    "Vampire Gaze",
    "Guillaume's Face",
    "Tal Rasha's Horadric Crest",
    "Guardian Angel",
    "Shaftstop",
    "Dracul's Grasp",
    "String of Ears",
    "Trang-Oul's Girth",
    "Goblin Toe",
    "Gore Rider",
    "Metalgrid",
    "Angelic Wings",
    "Angelic Halo",
    "Windforce",
    "M'avina's Caster",
    "Buriza-Do Kyanon",
    "Spellsteel",
    "Andariel's Visage",
    "Giant Skull",
    "Stealskull",
    "Crown of Thieves",
    "M'avina's True Sight",
    "M'avina's Embrace",
    "Twitchthroe",
    "Tyrael's Might",
    "M'avina's Icy Clutch",
    "M'avina's Tenet",
    "Eschuta's Temper",
    "The Oculus",
    "Crescent Moon",
    "Tal Rasha's Lidless Eye",
    "Gerke's Sanctuary",
    "Tal Rasha's Guardianship",
    "Ormus' Robes",
    "Frostburn",
    "Tal Rasha's Fine-Spun Cloth",
    "Tal Rasha's Adjudication",
    "Death's Fathom",
    "Snowclash",
    "Bartuc's Cut-Throat",
    "Death's Web",
    "Trang-Oul's Wing",
    "Homunculus",
    "Darkforce Spawn",
    "Trang-Oul's Guise",
    "Trang-Oul's Scales",
    "Rotting Fissure",
    "Marrowwalk",
    "Maelstrom",
    "Immortal King's Will",
    "Goldskin",
    "Infernostride",
    "Griswold's Redemption",
    "Immortal King's Soul Cage",
    "Immortal King's Pillar",
    "Immortal King's Stone Crusher",
    "Arreat's Face",
    "Immortal King's Forge",
    "Rune Master",
    "Sigon's Gage",
    "Sigon's Wrap",
    "Sigon's Sabot",
    "Demon Limb",
    "Razor's Edge",
    "Butcher's Pupil",
    "Alma Negra",
    "Griswold's Honor",
    "Sigon's Visor",
    "Leviathan",
    "Steelrend",
    "Lava Gout",
    "Magnus' Skin",
    "Islestrike",
    "Jalal's Mane",
    "Cerebus' Bite",
    "Spirit Keeper",
    "Arkaine's Valor",
    "Wizendraw",
    "Sander's Riprap",
    "Head Hunter's Glory",
    "Soul Drainer",
    "Atma's Scarab",
    "Plague Bearer",
    "Venom Grip",
    "The Eye of Etlich",
    "Raven Claw",
    "Widowmaker",
    "Azurewrath",
    "Lightsabre",
    "Ribcracker",
    "Tomb Reaver",
    "Wolfhowl",
    "Stormlash",
    "Earthshaker",
    "Ravenlore",
    "Witchwild String",
    "Eaglehorn",
    "Goldstrike Arch",
    "Cliffkiller",
    "Hexfire",
    "The Rising Sun",
    "Hsarus' Iron Stay",
    "Hsarus' Iron Heel",
    "Ghoulhide",
    "Cleglaw's Pincers",
    "Hone Sundan",
    "Lycander's Flank",
    "Stoneraven",
    "Arioc's Needle",
    "The Impaler",
    "Aldur's Rhythm",
    "Aldur's Stony Gaze",
    "Aldur's Deception",
    "Lacerator",
    "Warshrike",
    "Deathbit",
    "The Scalper",
    "Demon's Arch",
    "Gimmershred",
    "Wraith Flight",
    "Death Cleaver",
    "Dragonscale",
    "Lance Guard",
    "Spirit Ward",
    "Jade Talon",
    "Lycander's Aim",
    "Cow King's Hooves",
    "Shadow Dancer",
    "Natalya's Mark",
    "Natalya's Totem",
    "Natalya's Shadow",
  ],
  eth: [
    "Titan's Revenge",
    "Death Cleaver",
    "Rune Master",
    "Tomb Reaver",
    "Hone Sundan",
    "Lacerator",
    "Warshrike",
    "Deathbit",
    "The Scalper",
    "Demon's Arch",
    "Gimmershred",
    "Gargoyle's Bite",
  ],
};
